title: "RustでWEB開発基"
summary: "WEB開発チームに入るまえに抑えてほしいポイントを紹介"
topics: ["rust","web"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - start
  - framework
  - routing
  - html
  - json
  - error
  - get-post
  - validation
  - database
  - mail
  - cache
  - csrf
  - command
  - env
